# Generated by Django 3.1.2 on 2020-10-11 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20201011_2134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='userid',
        ),
    ]
