# Generated by Django 3.1.2 on 2020-10-11 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20201011_2211'),
        ('app', '0012_merge_20201011_2232'),
    ]

    operations = [
    ]
