# Generated by Django 3.1 on 2020-10-18 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_solution_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
