# Generated by Django 3.1 on 2020-10-17 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_problem_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='description',
        ),
    ]
