# Generated by Django 3.1 on 2020-10-11 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='myUser',
        ),
    ]
