# Generated by Django 3.1.2 on 2020-10-11 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20201011_1500'),
        ('app', '0002_problem_solutions'),
    ]

    operations = [
    ]
