# Generated by Django 3.1 on 2020-10-11 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20201011_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='userid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
