# Generated by Django 3.1 on 2020-10-17 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_problem_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
