# Generated by Django 3.1.2 on 2020-10-11 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_merge_20201011_1647'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Problem_solutions',
            new_name='Problem_solution',
        ),
    ]
