# Generated by Django 3.1.2 on 2020-10-11 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20201011_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='original_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
