# Generated by Django 3.1.1 on 2020-10-11 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_merge_20201011_1735'),
        ('app', '0007_auto_20201011_1716'),
    ]

    operations = [
    ]
