# Generated by Django 3.1.2 on 2020-10-11 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20201011_1716'),
        ('app', '0004_problem_userid'),
    ]

    operations = [
    ]
