# Generated by Django 3.1.2 on 2020-10-11 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_merge_20201011_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='like_posts',
            field=models.ManyToManyField(blank=True, related_name='like_users', to='app.Problem'),
        ),
        migrations.AddField(
            model_name='problem',
            name='like_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
