# Generated by Django 3.1.2 on 2020-10-11 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_problem_userid'),
        ('app', '0008_merge_20201011_1943'),
    ]

    operations = [
    ]
