# Generated by Django 3.1.2 on 2020-10-11 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20201011_2124'),
        ('app', '0009_merge_20201011_2033'),
    ]

    operations = [
    ]
