# Generated by Django 3.1.2 on 2020-10-17 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_merge_20201011_2204'),
        ('app', '0011_merge_20201011_2159'),
    ]

    operations = [
    ]
