# Generated by Django 3.1.2 on 2020-10-11 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20201011_2050'),
        ('app', '0011_merge_20201011_2159'),
    ]

    operations = [
    ]
