# Generated by Django 3.1.2 on 2020-10-11 22:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_merge_20201011_2202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='like_count',
        ),
        migrations.AddField(
            model_name='problem',
            name='userid',
            field=models.IntegerField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
