# Generated by Django 3.1.2 on 2020-10-11 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_merge_20201011_2211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='like_posts',
            new_name='like_problems',
        ),
    ]
