# Generated by Django 3.1 on 2020-10-11 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20201011_2211'),
        ('app', '0012_merge_20201011_2232'),
        ('app', '0011_merge_20201011_2201'),
    ]

    operations = [
    ]
